### ISSUE TITLE
decode errors with same pattern

### ISSUE THREAD

**Issue by tcong-aa** [Elnaril/uniswap-universal-router-decoder#10]
please check out those txs:
https://etherscan.io/tx/0x8b02d0ac0c11da014e04a027eaa49ddf7913e64eef29fcb64f9595d277425f46
https://etherscan.io/tx/0x802f46df800388276bc4901fb5eeb62630770491138af14239d4de3def2c33e6
https://etherscan.io/tx/0xbbacb5a789ea5e1f795f70b3a52ca953ae3fbf5eb96413ae4942b5f499641597
https://etherscan.io/tx/0xf5b500136df991d18faadfbda87282b07f00d7fbe3e5116e064881d951b0ad62

**Comment by Elnaril** [comment]
Hello!

Here is the decoded input for the first transaction (0x8b02d0ac0c11da014e04a027eaa49ddf7913e64eef29fcb64f9595d277425f46) :

```python
{'commands': b'\x00\x00\x08',
 'inputs': [(<Function V3_SWAP_EXACT_IN(address,uint256,uint256,bytes,bool)>,
   {'recipient': '0x0000000000000000000000000000000000000001',
    'amountIn': 539689947,
    'amountOutMin': 22539188087083765897187811,
    'path': b"\xda\xc1\x7f\x95\x8d.\xe5#\xa2 b\x06\x99E\x97\xc1=\x83\x1e\xc7\x00\x0b\xb8\xc0*\xaa9\xb2#\xfe\x8d\n\x0e\\O'\xea\xd9\x08<ul\xc2\x00'\x10}\x81F\xcf!\xe8\xd7\xcb\xe4`T\xe0\x15\x88 {Q\x19\x87)",
    'payerIsSender': True}),
  (<Function V3_SWAP_EXACT_IN(address,uint256,uint256,bytes,bool)>,
   {'recipient': '0xbe8BC29765E11894f803906Ee1055a344fDf2511',
    'amountIn': 4857209527,
    'amountOutMin': 0,
    'path': b"\xda\xc1\x7f\x95\x8d.\xe5#\xa2 b\x06\x99E\x97\xc1=\x83\x1e\xc7\x00\x01\xf4\xc0*\xaa9\xb2#\xfe\x8d\n\x0e\\O'\xea\xd9\x08<ul\xc2",
    'payerIsSender': True}),
  (<Function V2_SWAP_EXACT_IN(address,uint256,uint256,address[],bool)>,
   {'recipient': '0x0000000000000000000000000000000000000001',
    'amountIn': 57896044618658097711785492504343953926634992332820282019728792003956564819968,
    'amountOutMin': 201706613530196448705261836,
    'path': ['0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
     '0x7D8146cf21e8D7cbe46054e01588207b51198729'],
    'payerIsSender': False})],
 'deadline': 1686896447}
```

Are you talking about the `amountIn` for the V2 swap ? Otherwise, can you please describe your issue ?

**Comment by tcong-aa** [comment]
yes, the amoutIn in V2_SWAP_EXACT_IN is not right

**Comment by Elnaril** [comment]
You say it is not right because this amount (`2**255`) is obviously way too big to be the exact amount of weth used in the swap ? Or because you have encoded the input data (or you know it has been encoded) with another number ?

**Comment by tcong-aa** [comment]
![image](https://github.com/Elnaril/uniswap-universal-router-decoder/assets/18389929/4ef32983-8e8f-4438-bbdf-5882af82975d)

this is the real weth amountIn of the transaction above,
but the number decoded is 57896044618658097711785492504343953926634992332820282019728792003956564819968

**Comment by Elnaril** [comment]
Ok.
The `amountIn` for the `V2_SWAP_EXACT_IN` transaction comes from a `V3_SWAP_EXACT_IN` `amountOutMin`. So there is no way to be sure what is going to be the exact output amount at the moment the transaction is encoded.

To handle that, you can set the `amountIn` to 2**255 which is the constant `CONTRACT_BALANCE` defined [here](https://github.com/Uniswap/universal-router/blob/a7bcf5459f475407a5af0aba6e5b6196e9461e4c/contracts/libraries/Constants.sol#LL11C8-L11C8).
It instructs the router to use all its balance for the `in_token`.
Since the router received ~2.9 WETH from the `V3_SWAP_EXACT_IN` swap, it uses the exact same amount for the `V2_SWAP_EXACT_IN` swap.

Does it make sense ?

**Comment by Elnaril** [comment]
Closing as there is no error from the decoder.
Feel free to re-open it otherwise.

And thank you for your interest in this lib! :)

**Comment by tcong-aa** [comment]
thanks man, this is a very useful lib :)

**Comment by Elnaril** [comment]
Thanks for your feedback!! :)
Happy coding!
