### ISSUE TITLE
sell fail

### ISSUE THREAD

**Issue by 845793508** [Elnaril/uniswap-universal-router-decoder#15]
Can buy, but the authorization to sell has not been successful, could you write a sell the demo. Because I'm always permit2 there appear problem, we can not sell out

https://etherscan.io/tx/0x400ec8157e7615cc45987692a1311e7413a66e5a139a54b8e157c8f9b8c4cf14

**Comment by Elnaril** [comment]
Hello @845793508 
Do you confirm you have done the following approval steps:

To sell, you need to:

1. Approve the Permit2 contract using the token approve function
2. Use the UR `PERMIT2_PERMIT` function. This step can be chained with the swap function or be done before the swap

`PERMIT2_PERMIT` examples:
- [alone](https://github.com/Elnaril/uniswap-universal-router-decoder#how-to-encode-a-call-to-the-function-permit2_permit)
- [chained](https://github.com/Elnaril/uniswap-universal-router-decoder#how-to-chain-a-call-to-permit2_permit-and-v2_swap_exact_in-in-the-same-transaction)

You have not chained the `PERMIT2_PERMIT` function in your transaction, so did you use it in a previous one?
 

Some points of attention:

- deadlines and expiration
- Approve/permit amounts
- token balance
- token contract does not prevent you to sell (scam tokens)

**Comment by 845793508** [comment]
THIS IS MY  CODE

ur_address = Web3.to_checksum_address("0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD")
sy = '##############'
token_address = Web3.to_checksum_address('0x966e770030209c95f974f37edbde65d98e853354')

zj_address =Web3.to_checksum_address(w3.eth.account.from_key(sy).address)

# amount_in = token_blance_count(w3.to_checksum_address(token_address), zj_address)
amount_in =100000000000

data, signable_message = codec.create_permit2_signable_message(
Web3.to_checksum_address("0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"),
Wei(1461501637330902918203684832716283019655932542975), # max = 2**160 - 1
codec.get_default_expiration() + 2590200, # ERROR
0, # ERROR
ur_address,
codec.get_default_expiration(), # ERROR
1,
)

# 中间是池子费用
path = [token_address, weth]
encoded_input = (
codec
.encode
.chain()
.permit2_permit(data, signable_message)
.v2_swap_exact_in(FunctionRecipient.ROUTER, amount_in, 0, path, payer_is_sender=True)
.unwrap_weth(FunctionRecipient.SENDER, 0)
.build(codec.get_default_deadline())
)

nonce = w3.eth.get_transaction_count(zj_address)
trx_params = {
"from": zj_address,
"to": ur_address,
"gas": 21000 * 15,
"gasPrice": int(w3.eth.gas_price*1.4),
"chainId": 1,
"value": 0,
"nonce": nonce,
"data": encoded_input
}
# print(trx_params)
# exit()
signed_txn = w3.eth.account.sign_transaction(trx_params, private_key=sy)
tx_token = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
print('消息已经广播发送返回的信息为' + w3.to_hex(tx_token))

(expiration  AND nonce  AND deadline) error，因为我看返回的signable.body！=b'\x92U\x83n\x15\x87\x9ay\xcb\xcez\xc2B\xb6Z\xd2\xe4>\xd2n\x8b\xa8\xedl\xa9\x16\x8f\xcco\x88\xb3\xe0'

所以麻烦您帮忙看看

**Comment by Elnaril** [comment]
A few comments:
- when posting code, for readability sake, can you please make sure it is formatted as Python code, using the appropriate feature.
- Also, writing in English only would help to understand quicker
- I don't see any code about approving the Permit2 contract using the token approve function. Have you done it?
- you mention errors regarding the expiration, nonce and deadline. What errors did you get exactly?

**Comment by 845793508** [comment]
from web3 import Web3
from web3.types import HexBytes,HexStr,Wei
from uniswap_universal_router_decoder import FunctionRecipient, RouterCodec
from web3.middleware import geth_poa_middleware
from eth_account.datastructures import SignedMessage
from eth_account.signers.local import LocalAccount
from eth_account import Account


alchemy_url = "https://eth-mainnet.g.alchemy.com/v2/lWrjIDJ6cozkpIPxHH8SuETp7cCGbE3A"
w3 = Web3(Web3.HTTPProvider(alchemy_url))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)

weth = Web3.to_checksum_address('0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2')

ur_address = Web3.to_checksum_address("0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD")
sy = '#############'
token_address = Web3.to_checksum_address('0x966e770030209c95f974f37edbde65d98e853354')  # sell_token
zj_address =Web3.to_checksum_address('0x111987D7cb01ab55B04439626acCc4FaD9898350')



codec = RouterCodec()

def  sell_token():
    amount_in = 10000000000

    data, signable_message = codec.create_permit2_signable_message(
        token_address,
        Wei(1461501637330902918203684832716283019655932542975),  # max = 2**160 - 1
        codec.get_default_expiration(),
        0,
        ur_address,
        codec.get_default_expiration(),
        1,
    )

    #  signable_message.header == b'\x86jZ\xba!\x96j\xf9]lz\xb7\x8e\xb2\xb2\xfc\x919\x15\xc2\x8b\xe3\xb9\xaa\x07\xcc\x04\xff\x90>?('
    # signable_message.body == b'\xcd;\xb8\x06\xa3\x9b\x08\x0cc\x10\xfb\xd1j\xa9cC\x18\x06\xc8\xb7Sa\x8c^\xcco\xc2w\xf9\xef\x01\x19')

    account: LocalAccount = Account.from_key(sy)
    signed_message: SignedMessage = account.sign_message(signable_message)

    path = [token_address, weth]
    encoded_input = (
            codec
            .encode
            .chain()
            .permit2_permit(data, signable_message)
            .v2_swap_exact_in(FunctionRecipient.ROUTER, amount_in, 0, path, payer_is_sender=True)
            .unwrap_weth(FunctionRecipient.SENDER, 0)
            .build(codec.get_default_deadline())
    )

    nonce = w3.eth.get_transaction_count(zj_address)
    trx_params = {
            "from": zj_address,
            "to": ur_address,
            "gas": 21000 * 15,
            "gasPrice": int(w3.eth.gas_price*1.4),
            "chainId": 1,
            "value": 0,
            "nonce": nonce,
            "data": encoded_input
    }

    signed_txn = w3.eth.account.sign_transaction(trx_params, private_key=sy)
    tx_token = w3.eth.send_raw_transaction(signed_txn.rawTransaction)


sell_token()


# this is my code,is fail  url：https://etherscan.io/tx/0x400ec8157e7615cc45987692a1311e7413a66e5a139a54b8e157c8f9b8c4cf14

**Comment by Elnaril** [comment]
I still don't see any code about approving the Permit2 contract using the token approve function.

Unrelated to this issue: you don't need the poa middleware on the Ethereum chain.

**Comment by 845793508** [comment]
I don't know what to do you can write a about selling this token a code mode,thank you thank you,BOSS

**Comment by Elnaril** [comment]
When I have some time (not sure when though), I'll write a full example or even a tutorial about it.
Thanks for your interest in this lib! ;)

**Comment by cong235** [comment]
> I still don't see any code about approving the Permit2 contract using the token approve function.
> 
> Unrelated to this issue: you don't need the poa middleware on the Ethereum chain.

What is # Permit2 nonce? that is nonce of permit2 contract or sender nonce>
