### ISSUE TITLE
Hope you can give a sell token model

### ISSUE THREAD

**Issue by 845793508** [Elnaril/uniswap-universal-router-decoder#19]
Hope you can give a sell token model

**Comment by Elnaril** [comment]
@845793508 : will do when I have some spare time and if enough people are interested.
Thank you for your interest in this lib! :)

**Comment by sahancava** [comment]
please make a modal for sell tokens :) Need to have it :)

**Comment by tojepower** [comment]
hi, Is anyone able to sell the token using this module ? It shows the transfer failed, I tried many times to get it permitted and signed but didn't work as expected, please help.

**Comment by Elnaril** [comment]
Hello!
> Is anyone able to sell the token using this module ?

I can confirm you that plenty of people (including clients) are able to sell tokens using this lib! ;)

I don't have time to write a tutorial at the moment, but I take note of your interest in it! :)
When it's done, I'll announce it through Twitter and in this repo announcement section.

**Comment by cong235** [comment]
> Hello!
> 
> > Is anyone able to sell the token using this module ?
> 
> I can confirm you that plenty of people (including clients) are able to sell tokens using this lib! ;)
> 
> I don't have time to write a tutorial at the moment, but I take note of your interest in it! :) When it's done, I'll announce it through [Twitter](https://twitter.com/ElnarilDev) and in this repo [announcement page](https://github.com/Elnaril/uniswap-universal-router-decoder/discussions/categories/announcements).

Can you write a simple example to sell tokens? i tried but just show error FAIL_TRANSFER when exchange from customERC20 token to eth

**Comment by cong235** [comment]
> hi, Is anyone able to sell the token using this module ? It shows the transfer failed, I tried many times to get it permitted and signed but didn't work as expected, please help.

Did you fixed it?

**Comment by 845793508** [comment]
> @845793508：当我有空闲时间并且有足够多的人感兴趣时就会做。 感谢您对这个库的兴趣！:)

https://etherscan.io/tx/0x571c4aa33dcec33381c9ba868dbf69a55edfd48d89aafa57c735295d85b4346b  It was successful, but why don’t I have the tokens I purchased in my account?

**Comment by Elnaril** [comment]
Hello @845793508 

Can you please open a discussion in the [Q&A](https://github.com/Elnaril/uniswap-universal-router-decoder/discussions/categories/q-a) section as it is intended for questions? And anyway yours is not related to the sell model/documentation/tutorial.

Thanks! :)

**Comment by 845793508** [comment]
.v2_swap_exact_in(FunctionRecipient.ROUTER, int(amount_in * 0.05), int(min_amount_out * 0.05), path, payer_is_sender=False)
.v2_swap_exact_in(FunctionRecipient.ROUTER, int(min_amount_out), 0, path1, payer_is_sender=False)
.v2_swap_exact_in(FunctionRecipient.SENDER, int(amount_in * 0.95), int(min_amount_out * 0.95), path,
payer_is_sender=False)     //It was successful, but why don’t I have the tokens I purchased in my account?

**Comment by Elnaril** [comment]
Open a Q&A question if you want an answer

**Comment by 845793508** [comment]
> Open a Q&A discussion if you want an answer
I hope to realize buying and selling in one method. I buy a token for 0.1, then sell half of the tokens, and the remaining tokens go to my account.i don't know what i should do
