### ISSUE TITLE
Could you provide code for bsc chain?

### ISSUE THREAD

**Issue by JeffXu1** [Elnaril/uniswap-universal-router-decoder#21]
I want to use this code to generate signable_message for bsc chain, how should I change the code?

**Comment by Elnaril** [comment]
Hello @JeffXu1 
This lib has not been tested for BSC, but have you tried to just change the chain id to BSC one, which is 56?
Something like:

```python
# Permit signature
data, signable_message = codec.create_permit2_signable_message(
    token_address,
    amount,  # max = 2**160 - 1
    expiration,
    nonce,  # Permit2 nonce
    spender,  # The UR checksum address
    deadline,
    56,  # chain id
)
```

**Comment by JeffXu1** [comment]
hi, I have changed the chain id to test the signable_message, but the signable_message is different from which the uniswap app generated, you could check the chain log https://bscscan.com/tx/0x6d9c0392bf337afcdbad0e1f8100f51a30b8f7e776ecde1f3b3612e3da2f2ac8, thanks!

**Comment by Elnaril** [comment]
Hi @JeffXu1 !
I've just tested on a local BSC fork and it worked as expected, so I'm going to close this ticket.
When I have some spare time and if enough people are interested, I'll write a tutorial or an integration test on this part (See #19).
Thank you for your interest in this lib! :)

**Comment by JeffXu1** [comment]
hi, I try to use you code to decode information firstly from the chain log data,https://bscscan.com/tx/0x6d9c0392bf337afcdbad0e1f8100f51a30b8f7e776ecde1f3b3612e3da2f2ac8, then I use you code to generate signable_message, I hope the signable_message is same with the log on chain, but the results is diffrent, my code is as follows:
from uniswap_universal_router_decoder import RouterCodec
from web3 import Web3, Account
from web3.types import Wei

trx_input = "0x3593564c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000064e36df500000000000000000000000000000000000000000000000000000000000000020a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000160000000000000000000000000d691d9a68c887bdf34da8c36f63487333acfd103000000000000000000000000ffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000650af28f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fc91a3afd70395cd496c647d5a6cc9d4b2b7fad0000000000000000000000000000000000000000000000000000000064e36c9700000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000004194e76c40876170289ba6e0464c44f43d94b6bfa3384dc52533bc45c2be92e67348d58492717c6191387ba79774f484d3d1208dfeec7213b24b0b7d71e16d7bd21b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000006781f1825668c000000000000000000000000000000000000000000000000000144dcba8cc9642a900000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002bd691d9a68c887bdf34da8c36f63487333acfd10300271055d398326f99059ff775485246999027b3197955000000000000000000000000000000000000000000"  # the trx input to decode
codec = RouterCodec()
decoded_trx_input = codec.decode.function_input(trx_input)
print(decoded_trx_input)
test_data = b'\x94\xe7l@\x87ap(\x9b\xa6\xe0FLD\xf4=\x94\xb6\xbf\xa38M\xc5%3\xbcE\xc2\xbe\x92\xe6sH\xd5\x84\x92q|a\x918{\xa7\x97t\xf4\x84\xd3\xd1 \x8d\xfe\xecr\x13\xb2K\x0b}q\xe1m{\xd2\x1b'
print(test_data.hex())
command = b'\n\x00'
print(command.hex())
token_address = Web3.to_checksum_address('0xd691d9a68C887BDF34DA8c36f63487333ACfD103')
bnb_value = 1461501637330902918203684832716283019655932542975
amount = Wei(bnb_value)
expiration = 1695216271
nonce = 0
spender = Web3.to_checksum_address('0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD')
deadline = 1692626071
data, signable_message = codec.create_permit2_signable_message(
    token_address,
    amount,  # max = 2**160 - 1
    expiration,
    nonce,  # Permit2 nonce
    spender,  # The UR checksum address
    deadline,
    56,  # chain id
)
print(signable_message)
print(signable_message.header.hex())
print(signable_message.body.hex())
The result is:

**Comment by Elnaril** [comment]
Hello @JeffXu1 !
Are you sure you're using the exact same Permit2 expiration, nonce and deadline as the original transaction?
Are you sure the original transaction gave the max amount possible to  the Permit2 contract?
The slightest difference in the input details would explain a difference in the output message.

**Comment by Elnaril** [comment]
Actually it seems you're comparing the original **signed** message with the **signable** message given by the lib.
You would need to sign it first with the same key as the original one.

**Comment by JeffXu1** [comment]
Yes, you are right, I retry it and get the right signature inforamtion, thank you very much. In addition, I am tryingto write code to generate signature message on Arbitrum for other contracts? The chain log is https://arbiscan.io/tx/0x47732380c652f48b983f536beaa54a7feb239028ccb268c1af47af56c9661a6e, but the data structure seems different from you wrote before, could you help give some advice?

**Comment by Elnaril** [comment]
> Yes, you are right, I retry it and get the right signature inforamtion, thank you very much

Welcome! :)

>  In addition, I am tryingto write code to generate signature message on Arbitrum for other contracts? The chain log is https://arbiscan.io/tx/0x47732380c652f48b983f536beaa54a7feb239028ccb268c1af47af56c9661a6e, but the data structure seems different from you wrote before, could you help give some advice?

I don't know this contract, so I won't be able to help: you'll need to go through their doc if it exists ...

**Comment by JeffXu1** [comment]
i just want to write code to realize EIP712 structured data signing, i wonder if I could use your code to realize it, if yes, how to modify your code?

**Comment by Elnaril** [comment]
This is out of this lib's scope, sorry.
Please keep topics relevant to the Uniswap Universal Router only!
