### ISSUE TITLE
Add the support for  `PAY_PORTION` and `SWEEP` command

### ISSUE THREAD

**Issue by rahulthakkar796** [Elnaril/uniswap-universal-router-decoder#25]
It would be greatly appreciated if you could include support for the `PAY_PORTION` and `SWEEP` commands in your library. This would enable us to implement a swap fee feature for the hosted DEXs effectively, as it involves performing three commands simultaneously: one for the swap, another for paying a portion, and the third for sweeping. Unfortunately, Uniswap's documentation does not provide clear instructions on how to achieve this using the 'execute' method. Therefore, it would be highly beneficial if you could incorporate this functionality into your library.

**Comment by Elnaril** [comment]
Actually, they are the next UR functions I planned to implement but never had time to do so ...
I agree it would be a nice addition to the lib, though I can't tell when I can take some time for it.

Anyway, I'll post an announcement when it's done [here](https://github.com/Elnaril/uniswap-universal-router-decoder/discussions/categories/announcements) and [there](https://twitter.com/ElnarilDev).

Thank you for your interest in this lib! :)

**Comment by Elnaril** [comment]
Hello @rahulthakkar796 
FYI, I've just released the v1.0.0 which supports the Universal Router `PAY_PORTION` and `SWEEP` functions! :)

Closing as completed.
