### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nick2Nik** [Elnaril/uniswap-universal-router-decoder#38]
Hi There!
It seams they have changed something in contract logic.
The transaction that passes has data like this:
0x000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000f2e0200000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002b3c499c542cef5e3811e1192ce70d8cc03d5c33590000642791bca1f2de4661ed88a30c99a7a9449aa84174000000000000000000000000000000000000000000

Transactions with generated data fail. Generated date is this:
0x000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000f1b3000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174

**Comment by Elnaril** [comment]
Hello!
It looks like these are just partial data. For what sub-command are they? I'll need the whole data sent to the UR ...
Do you have a link to Etherscan?

**Comment by Nick2Nik** [comment]
Hi, bro!
Have a look for my test wallet.
https://polygonscan.com/address/0x9b38c515a731f4a4e9b879fb2c288582e8685edb

Execute failed - via decoder data. Success - direct via uni UI

Nikita

PS. Your product is wonderful! write me your evm wallet - I want to thank
you

ср, 17 янв. 2024 г. в 20:58, Elnaril ***@***.***>:

**Comment by Elnaril** [comment]
Hi!

> Have a look for my test wallet.
> https://polygonscan.com/address/0x9b38c515a731f4a4e9b879fb2c288582e8685edb

The successful swap was done using a V3 pool (command: 0x00), while the failed one was done using a V2 pool (0x08) which does not exist.

> PS. Your product is wonderful! write me your evm wallet - I want to thank you

Very happy you find it wonderful!! :) You will find an address in the wiki page footer: https://github.com/Elnaril/uniswap-universal-router-decoder/wiki

**Comment by Nick2Nik** [comment]
Thanks!
I'll try to manage chainging to v3 ))

чт, 18 янв. 2024 г. в 14:58, Elnaril ***@***.***>:

**Comment by Elnaril** [comment]
Thank you for your interest in this lib and happy coding! :)

**Comment by Nick2Nik** [comment]
TNX BRO!
^)
Happy coffe!
https://polygonscan.com/tx/0x21ba9f3fa9b940d4ad28a101dc78e18d42a3309c606f4e9d3e7e9e21e555bb60

**Comment by Elnaril** [comment]
Thank you so much @Nick2Nik for these coffees! Very much appreciated! :)

**Comment by Nick2Nik** [comment]
Hi bro!
Not making a tiket, sorry.

Why i'm failing?
https://bscscan.com/tx/0x41360b24c9377aae19f31937a423209a93f21b5ce7b17b4d2a7ce1891fe13c9b

сб, 20 янв. 2024 г. в 08:01, Elnaril ***@***.***>:
