### ISSUE TITLE
permit2_sign not work on bsc

### ISSUE THREAD

**Issue by freereaper** [Elnaril/uniswap-universal-router-decoder#47]
permit_data, signable_message = codec.create_permit2_signable_message(
            approve_token,
            allowance_amount,
            codec.get_default_expiration(365*24*3600),  # 30 days
            p2_nonce,
            UR_ADDRESS,
            codec.get_default_deadline(),  # 180 seconds
            56,
        )

signed_message = client.w3.eth.account.sign_message(signable_message,  private_key=wallet_key)

        encoded_input = (
                codec
                .encode
                .chain()
                .permit2_permit(permit_data, signed_message)
                .v2_swap_exact_in(FunctionRecipient.SENDER, amount_in, min_amount_out, path, payer_is_sender=True)
                .build(codec.get_default_deadline())
        )

i used the code to generate permit_data and signed_message, then add permit2_permit(permit_data, signed_message) to the call chain, the transaction fails. but if i signed in the pancake and swap once, then remove the permit2_permit from the sign, the code works like a charm.

**Comment by freereaper** [comment]
failed transcation (with permit2_perimit) decoded data:

> (<Function execute(bytes,bytes[],uint256)>, {'commands': b'\n\x08', 'inputs': [(<Function PERMIT2_PERMIT(((address,uint160,uint48,uint48),address,uint256),bytes)>, {'struct': {'details': {'token': '0x55d398326f99059fF775485246999027B3197955', 'amount': 1461501637330902918203684832716283019655932542975, 'expiration': 1743158090, 'nonce': 0}, 'spender': '0x1A0A18AC4BECDDbd6389559687d1A73d8927E416', 'sigDeadline': 1711622270}, 'data': b'>\xb4\x145\xc4t[]zS\xad\xc7\x9e\x926\x9c\xafR-.O\x1cM\x85;\xd6W\x8fy\xdaOluc\xac\xbc\xeb\x01\xfbO|\xd2\r|\xc7\x00\xd6S%s1\x8c\x8a \xcd\x9c\x1f#\x1c\xe8|`\xa5\xc1\x1c'}, {'revert_on_fail': True}), (<Function V2_SWAP_EXACT_IN(address,uint256,uint256,address[],bool)>, {'recipient': '0x0000000000000000000000000000000000000001', 'amountIn': 1000000000000000000, 'amountOutMin': 500000000000000000000, 'path': ['0x55d398326f99059fF775485246999027B3197955', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56', '0xF700D4c708C2be1463E355F337603183D20E0808'], 'payerIsSender': True}, {'revert_on_fail': True})], 'deadline': 1711622270})

success transaction without permit2_permit decode data:

> (<Function execute(bytes,bytes[],uint256)>, {'commands': b'\x08', 'inputs': [(<Function V2_SWAP_EXACT_IN(address,uint256,uint256,address[],bool)>, {'recipient': '0x0000000000000000000000000000000000000001', 'amountIn': 10000000000000000000, 'amountOutMin': 500000000000000000000, 'path': ['0x55d398326f99059fF775485246999027B3197955', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56', '0xF700D4c708C2be1463E355F337603183D20E0808'], 'payerIsSender': True}, {'revert_on_fail': True})], 'deadline': 1711623620})

**Comment by Elnaril** [comment]
Hello @freereaper !

Are you sure:
- you use the right permit2 nonce?
- you have approved the permit2 contract to the token contract?

If yes, can you please share the link to the failing transaction? (one you did not "override" with one from pancake)

**Comment by freereaper** [comment]
Thanks for  your help

Yes, approve the permit2 contract to token contrace is done in the first step:

```
       contract_function = approve_token_ca.functions.approve(
                permit2_address,
                permit2_allowance
        )

```
Transaction:
https://bscscan.com/tx/0x186e377e13ff5245c3e4ca5aa66c6558f0313713932f49924b132aca18117677


And this is the one from pancake, sign and swap
https://bscscan.com/tx/0xfa95224b52a245dbe2f4d5414d301f588d43fe7d85b12cb8c3f733608806d66a

I get the permit2 nonce from the below code and use it in the  codec.create_permit2_signable_message.
:
```
    p2_amount, p2_expiration, p2_nonce = permit2Contract.functions.allowance(
        wallet,
        approve_token,
        UR_ADDRESS
    ).call()
```
This is the fail one with sign and swap:
https://bscscan.com/tx/0x6ba61492ec778ea39861ebc1dc3a5d75caab8643a4b3013a609c56a810a1d72d

**Comment by Elnaril** [comment]
Ok, thanks! I'm a bit busy at the moment, but I'll try to look into it over the week-end.

**Comment by freereaper** [comment]
Thanks , wait for the solution.

**Comment by freereaper** [comment]
Hello, have solved the issue, pancake use different permit2 address.

https://github.com/Elnaril/uniswap-universal-router-decoder/pull/48

**Comment by Elnaril** [comment]
Great! Thanks for the PR. Will review it asap.
