### ISSUE TITLE
Add support for other EVMs

### ISSUE THREAD

**Issue by Lytes** [Elnaril/uniswap-universal-router-decoder#57]
**Describe the feature you'd like**
Allow multi-chain usage by making it possible to set permit2 address (which is currently hard coded for ethereum mainnet)
 https://github.com/Elnaril/uniswap-universal-router-decoder/blob/dec6c20a42749447d960be559a5fb1f149ee2cd6/uniswap_universal_router_decoder/_constants.py#L23C46-L23C88

OR 
Add a dict for all the possible uniswap deployments so users only have to specify chain
https://docs.uniswap.org/contracts/v3/reference/deployments

**Comment by Elnaril** [comment]
Hello @Lytes ! I believe this enhancement has been done in #52 which allows the overriding of the permit2 address.
It will be part of the next version, though not sure when, as I want to add a few other features as well ...
