### ISSUE TITLE
How to encode the `UNWRAP_WETH`

### ISSUE THREAD

**Issue by Jonkrua** [Elnaril/uniswap-universal-router-decoder#7]
How to encode the `UNWRAP_WETH` ?

**Comment by Elnaril** [comment]
Hello @Jonkrua !
Encoding  the `UNWRAP_WETH` function is not yet supported by this lib.
I'm rather busy at the moment, but I plan to implement it sooner or later (sooner if people are interested in it).

**Comment by Elnaril** [comment]
Thank you for your interest in this lib!

**Comment by Jonkrua** [comment]
> Thank you for your interest in this lib!
BTW, Is there any lib to decode the univ3 multicall?

**Comment by Elnaril** [comment]
Not sure if there is a lib to do that. I just use the corresponding ABI for each command.

**Comment by twb725** [comment]
Encode the UNWRAP_WETH function , plz help , I need this function, thanks.

**Comment by twb725** [comment]
Encode the UNWRAP_WETH function , plz help , I need this function, thanks.

> Hello @Jonkrua ! Encoding the `UNWRAP_WETH` function is not yet supported by this lib. I'm rather busy at the moment, but I plan to implement it sooner or later (sooner if people are interested in it).

**Comment by Elnaril** [comment]
Hello @twb725  and thank you for letting me know your interest.
This lib is used more and more, so I plan to add this function in the "near" future.

**Comment by 845793508** [comment]
What is the acc? Then how do you sell

**Comment by Elnaril** [comment]
This is explained here:
- [Tutorial](https://github.com/Elnaril/uniswap-universal-router-decoder/discussions/9)
- [Usage](https://github.com/Elnaril/uniswap-universal-router-decoder/blob/master/README.md#usage)
- [Example](https://github.com/Elnaril/uniswap-universal-router-decoder/blob/master/integration_tests/main.py)

Please use this ticket for `UNWRAP_WETH` related issue/discussion.
Feel free to open another one if you have a _specific_ issue with the lib.

**Comment by Elnaril** [comment]
@Jonkrua , @twb725 , v0.9.0 has just been released with support for `UNWRAP_WETH`! :)
