### ISSUE TITLE
How to do a swap ?

### ISSUE THREAD

**Issue by Thekthekthek** [Elnaril/uniswap-universal-router-decoder#8]
I would love to see a sample of transaction for a swap, for example :

"""

from uniswap_universal_router_decoder import FunctionRecipient, RouterCodec

codec = RouterCodec()

# Permit signature
data, signable_message = codec.create_permit2_signable_message(
   "0x...",
    amount,  # max = 2**160 - 1 (I don't get how to do this part for example)
    expiration, (same thing)
    nonce,  # Permit2 nonce (same thing)
    spender,  # UR 
    deadline, (same thing)
    1,  # chain id
)

# Then you need to sign the message:
signed_message = acc.sign_message(signable_message)  # where acc is your LocalAccount

# Permit + v2 swap encoding
path = [token_in_address, token_out_address]
encoded_data = (
    codec
        .encode
        .chain()
        .permit2_permit(data, signed_message)
        ----Same goes for code below----
        .v2_swap_exact_in(FunctionRecipient.SENDER, Wei(10**18), Wei(0), path) 

        .build(deadline)
)

# Then in your transaction dict:
transaction["data"] = encoded_data

# you can now sign and send the transaction to the UR

"""

I would really appreciate, already love your code btw, but I would love to understand it better and use it better :) good job bro

**Comment by Elnaril** [comment]
Hello @Thekthekthek !

> I would really appreciate, already love your code btw, but I would love to understand it better and use it better :) good job bro

Thank you !! :)

I understand that some parts of this code may be a bit puzzling as this library is intended for developers already comfortable with not only all the blockchain basics and web3.py, but also with previous Uniswap routers. So, going through all these concepts would be out of scope here.
But, if you just need a code sample, maybe the [integration tests](https://github.com/Elnaril/uniswap-universal-router-decoder/blob/master/integration_tests/main.py) will help ? 

Having said that, I plan to write a tutorial on how to do a swap with this lib and [uniswap-smart-path](https://github.com/Elnaril/uniswap-smart-path) (though not sure when as I'm super busy). So, considering your request, I'll try to make it a bit more accessible.

**Comment by Elnaril** [comment]
Hello @Thekthekthek !
I've written this [tutorial](https://hackernoon.com/how-to-buy-a-token-on-the-uniswap-universal-router-with-python)
Hopefully it will give you a better understanding on how to use the UR codec! :)

**Comment by cong235** [comment]
> I would love to see a sample of transaction for a swap, for example :
> 
> """
> 
> from uniswap_universal_router_decoder import FunctionRecipient, RouterCodec
> 
> codec = RouterCodec()
> 
> # Permit signature
> data, signable_message = codec.create_permit2_signable_message( "0x...", amount, # max = 2**160 - 1 (I don't get how to do this part for example) expiration, (same thing) nonce, # Permit2 nonce (same thing) spender, # UR deadline, (same thing) 1, # chain id )
> 
> # Then you need to sign the message:
> signed_message = acc.sign_message(signable_message) # where acc is your LocalAccount
> 
> # Permit + v2 swap encoding
> path = [token_in_address, token_out_address] encoded_data = ( codec .encode .chain() .permit2_permit(data, signed_message) ----Same goes for code below---- .v2_swap_exact_in(FunctionRecipient.SENDER, Wei(10**18), Wei(0), path)
> 
> ```
>     .build(deadline)
> ```
> 
> )
> 
> # Then in your transaction dict:
> transaction["data"] = encoded_data
> 
> # you can now sign and send the transaction to the UR
> """
> 
> I would really appreciate, already love your code btw, but I would love to understand it better and use it better :) good job bro

How you can get Nonce of Permit2 auto?
